apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ordercapture-deployment
  namespace: k8schallenge-mongorabbitmq
  labels:
    app: ordercapture
spec:
  selector:
    matchLabels:
      app: ordercapture
  template:
    metadata:
      namespace: k8schallenge-mongorabbitmq
      labels:
        app: ordercapture
    spec:
      containers:
      - name: ordercapture
        #image: sabbour/captureorderack:latest # golang
        image: sabbour/captureorderack-netcore:latest # netcore
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
        env:
        - name: MONGOURL
          value: "mongodb://mongodb-mongodb.k8schallenge-mongorabbitmq.svc.cluster.local"
        - name: AMQPURL
          value: "amqp://admin:password@rabbitmq-rabbitmq.k8schallenge-mongorabbitmq.svc.cluster.local:5672"
        - name: APPINSIGHTS_KEY
          value: "db755b02-c972-4f4d-ae93-cccbd98403c9"
        - name: CHALLENGEAPPINSIGHTS_KEY
          value: "db755b02-c972-4f4d-ae93-cccbd98403c9"
        - name: TEAMNAME
          value: "sabbour-test"
---
kind: Service
apiVersion: v1
metadata:
  name: ordercapture-service
  namespace: k8schallenge-mongorabbitmq
spec:
  selector:
    app: ordercapture
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordercapture-autoscaler
  namespace: k8schallenge-mongorabbitmq
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: ordercapture-deployment
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40