apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: listener-deployment
  namespace: k8schallenge-cosmoseventhub  
  labels:
    app: listener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      namespace: k8schallenge-cosmoseventhub      
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: sabbour/eventhublistenerack:latest
        imagePullPolicy: Always        
        env:
        - name: TEAMNAME
          value: "sabbour-test"
        - name: PROCESSENDPOINT
          value: "http://fulfillorder.k8schallenge-cosmoseventhub.svc.cluster.local:8080/v1/order/"
        - name: EVENTHUBCONNSTRING
          value: "Endpoint=sb://sabbourcapture.servicebus.windows.net/;SharedAccessKeyName=TestPolicy;SharedAccessKey=2KHYwfOvBfchurrWXZkbeqh6j5MB1bfh1x1J7KYAiNY=;EntityPath=ehub"
        - name: EVENTHUBPATH
          value: ehub