apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: fulfillor-deployment
  namespace: k8schallenge-cosmoseventhub    
  labels:
    app: fulfillor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfillor
  template:
    metadata:
      namespace: k8schallenge-cosmoseventhub  
      labels:
        app: fulfillor
    spec:
      containers:
      - name: fulfillor
        image: sabbour/fulfillorderack:latest
        env:
        - name: TEAMNAME
          value: "sabbour-test"
        - name: MONGOURL
          value: "mongodb://sabbourordercapture:YftliYqKseSNN4cedwLs4o1itApGLs6hMaouPKv4MHVGMbH3lfv9085mOVyZEx0JEUcKsIJUH6yVbPL24f83vQ==@sabbourordercapture.documents.azure.com:10255/?ssl=true&replicaSet=globaldb"
        volumeMounts:
        - name: azurevol
          mountPath: /orders
      volumes:
        - name: azurevol
          persistentVolumeClaim:
           claimName: azurefile
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8schallenge-cosmoseventhub 
  name: azurefile
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  namespace: k8schallenge-cosmoseventhub    
  name: fulfillorder
spec:
  type: ClusterIP
  selector:
    app: fulfillor 
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080



    