apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ordercapture-deployment
  namespace: k8schallenge-cosmoseventhub
  labels:
    app: ordercapture
spec:
  selector:
    matchLabels:
      app: ordercapture
  template:
    metadata:
      namespace: k8schallenge-cosmoseventhub
      labels:
        app: ordercapture
    spec:
      containers:
      - name: ordercapture
        #image: sabbour/captureorderack:preview # golang
        image: sabbour/captureorderack-netcore:preview # netcore
        imagePullPolicy: Always        
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
        env:
        - name: MONGOURL
          value: "mongodb://sabbourordercapture:YftliYqKseSNN4cedwLs4o1itApGLs6hMaouPKv4MHVGMbH3lfv9085mOVyZEx0JEUcKsIJUH6yVbPL24f83vQ==@sabbourordercapture.documents.azure.com:10255/?ssl=true&replicaSet=globaldb"
        - name: AMQPURL
          value: "amqps://TestPolicy:2KHYwfOvBfchurrWXZkbeqh6j5MB1bfh1x1J7KYAiNY=@sabbourcapture.servicebus.windows.net/ehub"
        - name: APPINSIGHTS_KEY
          value: "db755b02-c972-4f4d-ae93-cccbd98403c9"
        - name: CHALLENGEAPPINSIGHTS_KEY
          value: "db755b02-c972-4f4d-ae93-cccbd98403c9"
        - name: TEAMNAME
          value: "sabbour-test"
---
kind: Service
apiVersion: v1
metadata:
  name: ordercapture-service
  namespace: k8schallenge-cosmoseventhub
spec:
  selector:
    app: ordercapture
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordercapture-autoscaler
  namespace: k8schallenge-cosmoseventhub
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: ordercapture-deployment
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40