# Site settings
title: "The Azure Challenge: Kubernetes"
description: ""
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty
#author: "John Doe"

# Build settings
kramdown:
  input: GFM

# Third-party services
# just leave empty to disable it
#google_analytics:
#disqus_shortname: hnbloggithub


permalink: /themes/:title/



gems: [jekyll-paginate]



highlighter: pygments

paginate: 20



markdown: rdiscount

rdiscount:

    extensions: ['smart']



exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']