version: '3'

services:
    captureorderack:
        build: ../../../../../code/captureorderack/.
        env_file:
            - .env
        ports:
            - 8080:8080
    fulfillorderack:
        build: ../../../../../code/fulfillorderack/.
        env_file:
            - .env
        ports:
            - 8081:8080
    eventhublistenerack:
        build: ../../../../../code/eventhublistenerack/.
        env_file:
            - .env