apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: listener-deployment
  namespace: k8schallenge-mongorabbitmq  
  labels:
    app: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      namespace: k8schallenge-mongorabbitmq      
      labels:
        app: listener
    spec:
      containers:
      - name: listener
        image: sabbour/rabbitmqlistenerack:latest
        imagePullPolicy: Always                
        env:
        - name: TEAMNAME
          value: "sabbour-test"
        - name: PROCESSENDPOINT
          value: 'http://fulfillorder.k8schallenge-mongorabbitmq.svc.cluster.local:8080/v1/order/'
        - name: RABBITMQHOST
          value: 'amqp://admin:password@rabbitmq-rabbitmq.k8schallenge-mongorabbitmq.svc.cluster.local:5672'
        - name: PARTITIONKEY
          value: '0'